- README.md
In this case, the title is self explanatory.
> Clean up README.md to remove redundant information

- backend/src/config/db.ts
added node_modules to .gitignore
> added node_modules to .gitignore

- backend/src/config/db.ts
- backend/src/models/users-models.ts
refactor: use pool instead of client for database connections
- Jira Ticket: Scrum 27
- [ ✅] My code follows the style guidelines of this project.
- [ ✅] I have reviewed the Git Workflow document for our team.
> refactor: use pool instead of client for database connections

- backend/src/controllers/users-controllers.ts
- backend/src/models/users-models.ts
Add validation checks to register functionality to see if email/user already exists and return the appropriate response.
- Jira Ticket: 27
> Add validation checks to register to see if email/user already exists

- backend/src/controllers/users-controllers.ts
- backend/src/middleware/users-middleware.ts
- backend/src/routes/users-routes.ts
> updated user login functionality

- backend/README.md
Create readme for backend so other devs can run it.
- [ NA] My code follows the style guidelines of this project.
- [NA ] I have performed a self-review of my code.
- [ NA] I have added tests that prove my fix is effective or that my feature works.
- [NA ] I have reviewed the Git Workflow document for our team.
> Create readme for backend so other devs can run it.

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/consts.tsx
- client/src/pages/LandingPage.tsx
> Landing page

- backend/package-lock.json
- backend/package.json
- backend/src/app.ts
Add CORS support so frontend can talk to backend
> add cors support

- backend/package-lock.json
- backend/src/app.ts
- backend/src/setup.sql
- client/src/consts.tsx
- [ ✅ ] My code follows the style guidelines of this project.
- [✅  ] I have performed a self-review of my code.
- [✅  ] I have added tests that prove my fix is effective or that my feature works.
- [ ✅ ] I have reviewed the Git Workflow document for our team.
> added queries table

- backend/src/config/db.ts
- backend/src/config/env.ts
- backend/src/controllers/users-controllers.ts
- backend/src/middleware/users-middleware.ts
- backend/src/routes/queries-routes.ts
- backend/src/server.ts
Add middleware to verify a users JWT token and create sample protected route to ensure only users with a correct JWT token can access that route.
> add middleware to verify users JWT token and create sample protected route

- backend/src/controllers/queries-controllers.ts
- backend/src/controllers/users-controllers.ts
- backend/src/models/queries-models.ts
- backend/src/routes/queries-routes.ts
Adds endpoints to edit and delete user queries (only for logged in users with a valid JWT token!)
- Jira Ticket: Scrum 66
- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my code.
> Adds ability to edit and delete user queries

- backend/src/controllers/queries-controllers.ts
- backend/src/middleware/queries-middleware.ts
- backend/src/models/queries-models.ts
- backend/src/routes/queries-routes.ts
- [ ✅] My code follows the style guidelines of this project.
- [ ✅] I have performed a self-review of my code.
- [ ✅] I have added tests that prove my fix is effective or that my feature works.
> fetching all queries for a user and specific user queries

- backend/src/controllers/users-controllers.ts
- [ ✅ ] My code follows the style guidelines of this project.
- [ ✅ ] I have performed a self-review of my code.
- [ ✅ ] I have added tests that prove my fix is effective or that my feature works.
- [  ✅] I have reviewed the Git Workflow document for our team.
> added username to token

- backend/src/controllers/queries-controllers.ts
- backend/src/controllers/users-controllers.ts
- backend/src/middleware/queries-middleware.ts
- backend/src/models/queries-models.ts
- backend/src/models/users-models.ts
- backend/src/setup.sql
- [ ✅ ] My code follows the style guidelines of this project.
- [  ✅] I have performed a self-review of my code.
- [  ✅] I have added tests that prove my fix is effective or that my feature works.
- [  ✅] I have reviewed the Git Workflow document for our team.
> added output and constraint field to queries table

- backend/src/app.ts
> updates token verification middleware

- makefile
> adds makefile

- client/public/_redirects
- client/src/App.tsx
- client/src/main.tsx
- client/src/pages/MainPage.tsx
- client/static.json
- client/vite.config.ts
> handles history fetch errors

- client/public/_redirects
- client/src/App.tsx
- client/src/main.tsx
- client/src/pages/MainPage.tsx
- client/static.json
- client/vite.config.ts
Reverts chingu-voyages/V54-tier3-team-35#61
> Revert "handles history fetch errors"

- client/src/components/AuthForm.tsx
- client/src/components/ContributionForm/ContributionForm.tsx
- client/src/components/ContributionForm/Sidebar.tsx
> Removed unused import

- client/public/_redirects
- client/vite.config.ts
> static deployment setup

- backend/src/controllers/query-ai-controllers.ts
- client/src/components/ContributionForm/ContributionForm.tsx
- client/src/components/ContributionForm/FormFields.tsx
- client/src/components/ContributionForm/ResultDisplay.tsx
- client/src/components/ContributionForm/Sidebar.tsx
- client/src/components/ContributionForm/useContributionForm.tsx
- client/src/utils/utils.ts
- [ ✅] I have performed a self-review of my code.
- [ ✅] I have reviewed the Git Workflow document for our team.
> added edit inputs for previous queries that are in the history sidebar.

- client/src/components/AuthForm.tsx
> sets loading state for failed validations

- client/index.html
- client/src/components/ContributionForm/Sidebar.tsx
- client/src/components/Footer.tsx
- client/src/components/gif_animation.tsx
- client/src/pages/LandingPage.tsx
- client/src/pages/MainPage.tsx
- [ ✅ ] My code follows the style guidelines of this project.
- [  ✅] I have performed a self-review of my code.
- [  ✅] I have added tests that prove my fix is effective or that my feature works.
- [ ✅ ] I have reviewed the Git Workflow document for our team.
> styling changes to landing page

- client/index.html
- client/src/components/ContributionForm/Sidebar.tsx
- client/src/components/Footer.tsx
- client/src/components/GifAnimation.tsx
- client/src/index.css
- client/src/pages/LandingPage.tsx
> styling update

- backend/src/controllers/queries-controllers.ts
> Fix minor typos

- backend/src/controllers/queries-controllers.ts
Another minor spelling mistake.
> minor spelling fix

- backend/src/models/users-models.ts
Case sensitivity on table name fixed.
> Case sensitivity on table name fixed.

- backend/package-lock.json
- backend/package.json
- backend/src/controllers/queries-controllers.ts
- backend/src/models/queries-models.ts
- client/package-lock.json
- client/package.json
Update dependencies to resolve dependabot security warnings + fix copilot complains
> Update dependencies to resolve dependabot security warnings + fix copilot complains

- backend/src/app.ts
> only import swagger in development

- backend/src/app.ts
- backend/src/config/db.ts
- backend/src/config/env.ts
- client/netlify.toml
- docker-compose.yml
> developmet cors update

- backend/src/app.ts
- backend/src/config/db.ts
- backend/src/config/env.ts
- client/netlify.toml
- docker-compose.yml
Reverts chingu-voyages/V54-tier3-team-35#88
> Revert "developmet cors update"

- backend/src/app.ts
- backend/src/config/db.ts
- backend/src/config/env.ts
- client/netlify.toml
- docker-compose.yml
Reverts chingu-voyages/V54-tier3-team-35#90
> Revert "Fix/deployments"

- client/src/components/ContributionForm/FormFields.tsx
Add description inside textarea (instead of above it) to reduce need for the user to scroll on the chat page.
> Add description into textarea to reduce need for the user to scroll

- backend/README.md
- backend/src/app.ts
- backend/src/config/env.ts
- backend/src/controllers/query-ai-controllers.ts
> Dont hardcode CORS domains

- client/src/components/ContributionForm/ContributionForm.tsx
- client/src/components/ContributionForm/Sidebar.tsx
> Update sidebar to use cards

- backend/src/controllers/query-ai-controllers.ts
- backend/src/services/queries.ts
- client/src/components/ContributionForm/useContributionForm.tsx
> adds queries create service to query-ai controller
